[tool.poetry]
name = "curse-api"
version = "0.2.0"
description = "A simple curseforge api wrapper"
authors = ["Stinky-c <60587749+Stinky-c@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
chili = "^1.7.1"
httpx = "^0.23.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^0.21.0"
pytest = "^7.1.3"
tox = "^3.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
